version: '3'
services:
  relay:
    image: jusranotheridea/foundryvtt-rest-api-relay:latest
    container_name: foundryvtt-rest-api-relay
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - PORT=3010
      # Add other environment variables here
    volumes:
      - ./data:/app/data
    restart: unless-stopped