# fly.toml app configuration file
app = 'foundryvtt-rest-api-relay'
primary_region = 'ord'

[build]

[http]
  # This is the port Fly.io will expose to the internet
  port = 3010

[http_service]
  # This is the port your app listens on inside the container
  internal_port = 3010
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  force_instance_key = true
  
  # Add restart_machine_strategy for more graceful handling
  restart_machine_strategy = "rolling"
  
  [[http_service.checks]]
    grace_period = "45s"  # Increased from 30s to allow more time for Redis reconnection
    interval = "30s"
    method = "GET"
    path = "/health"
    timeout = "10s"  # Increased from 5s

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[vm.mounts]]
  source = "myapp_data"
  destination = "/data"
  
[env]
  ENABLE_REDIS = "true"