# fly.toml app configuration file
app = 'foundryvtt-rest-api-relay'
primary_region = 'ord'

[build]

[http]
  # This is the port Fly.io will expose to the internet
  port = 3010

[http_service]
  # This is the port your app listens on inside the container
  internal_port = 3010
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  
  [[http_service.checks]]
    grace_period = "10s" 
    interval = "30s"
    method = "GET"
    path = "/health"
    timeout = "5s"

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  # Remove sticky_sessions if you configured them before
  # Let the app handle the routing with Redis instead

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  REDIS_URL = "${FLY_REDIS_FOUNDRY_REST_API_REDIS_URL}"
