---
version: "3.8"

services:

  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    restart: "always"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - SUBDOMAINS=YOUR_DUCK_DNS_HOSTNAME_DOMAIN
      - TOKEN=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    restart: "always"
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - URL=YOUR_DUCK_DNS_HOSTNAME_DOMAIN.duckdns.org
      - VALIDATION=http
      - DUCKDNSTOKEN=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
      - EMAIL=ANY_VALID_EMAIL_YOU_WANT_TO_USE@gmail.com
    volumes:
      - ./data/swag/config:/config
    ports:
      - 80:80
      - 443:443
      - 3010:3010

  foundryapp:
    image: felddy/foundryvtt:12
    container_name: foundryapp
    hostname: foundryapp
    restart: "always"
    volumes:
      - type: bind
        source: ./data/app
        target: /data
    environment:
      #- FOUNDRY_PASSWORD=
      #- FOUNDRY_USERNAME=
      - FOUNDRY_ADMIN_KEY=YOUR_PASSWORD_FOUNDRY
      - CONTAINER_CACHE=/data/container_cache
      # - CONTAINER_CACHE_SIZE=
      # - CONTAINER_PATCHES=/data/container_patches
      # - CONTAINER_PATCH_URLS=
      #   https://raw.githubusercontent.com/felddy/...
      #   https://raw.githubusercontent.com/felddy/...
      - CONTAINER_PRESERVE_CONFIG=true
      # - CONTAINER_URL_FETCH_RETRY=0
      - CONTAINER_VERBOSE=true
      # - FOUNDRY_AWS_CONFIG=
      # - |
      #   FOUNDRY_DEMO_CONFIG={
      #   "worldName": "demo-world",
      #   "sourceZip": "/data/demo-world.zip",
      #   "resetSeconds": 3600
      #   }
      - FOUNDRY_COMPRESS_WEBSOCKET=true
      # - FOUNDRY_GID=foundry
      # - FOUNDRY_HOSTNAME=
      # - FOUNDRY_HOT_RELOAD=false
      # - FOUNDRY_IP_DISCOVERY=
      - FOUNDRY_LANGUAGE=en.core
      #- FOUNDRY_LOCAL_HOSTNAME=
      - FOUNDRY_LICENSE_KEY=YYYY-YYYY-YYYY-YYYY-YYYY-YYYY
      - FOUNDRY_MINIFY_STATIC_FILES=true
      # - FOUNDRY_PASSWORD_SALT=
      # - FOUNDRY_PROTOCOL=
      # - FOUNDRY_PROXY_PORT=
      # - FOUNDRY_PROXY_SSL=false
      # - FOUNDRY_RELEASE_URL=
      # - FOUNDRY_ROUTE_PREFIX=ddm
      # - FOUNDRY_SSL_CERT=
      # - FOUNDRY_SSL_KEY=
      # - FOUNDRY_TELEMETRY=
      # - FOUNDRY_UID=foundry
      - FOUNDRY_UPNP=true
      # - FOUNDRY_UPNP_LEASE_DURATION=
      # - FOUNDRY_VERSION=12.331
      - FOUNDRY_WORLD=world-test
      # - TIMEZONE=US/Eastern
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
        mode: host

  foundryrelay:
    image: threehats/foundryvtt-rest-api-relay:latest
    container_name: foundryrelay
    restart: "always"
    mem_limit: 256m
    hostname: foundryrelay
    # Commented we use the port on the proxy
    # ports:
    #   - "3010:3010"
    environment:
      - NODE_ENV=production
      - PORT=3010
    volumes:
      - ./data/relay:/app/data
    command: pnpm local
